begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select no_plan();
set local request.jwt.claims = '{}';
-- M1.2 now permits named authenticated reads; anonymous/default-deny invariants remain.
insert into public.organizations (id,name,code,type) values ('94000000-0000-4000-8000-000000000001','Protected','RLS-TEST','OTHER');
insert into auth.users(id) values ('95000000-0000-4000-8000-000000000001');
-- Profile provisioned by M1.3 trigger.
select ok((select relrowsecurity from pg_class where oid='public.countries'::regclass),'countries RLS enabled');
select ok(not exists(select 1 from pg_policy where polrelid='public.countries'::regclass and 0=any(polroles)),'countries has no policy for PUBLIC');
select ok((select count(*)>0 from public.countries),'countries contains fixtures visible to trusted owner');
select ok((select relrowsecurity from pg_class where oid='public.administrative_areas'::regclass),'administrative_areas RLS enabled');
select ok(not exists(select 1 from pg_policy where polrelid='public.administrative_areas'::regclass and 0=any(polroles)),'administrative_areas has no policy for PUBLIC');
select ok((select count(*)>0 from public.administrative_areas),'administrative_areas contains fixtures visible to trusted owner');
select ok((select relrowsecurity from pg_class where oid='public.organizations'::regclass),'organizations RLS enabled');
select ok(not exists(select 1 from pg_policy where polrelid='public.organizations'::regclass and 0=any(polroles)),'organizations has no policy for PUBLIC');
select ok((select count(*)>0 from public.organizations),'organizations contains fixtures visible to trusted owner');
select ok((select relrowsecurity from pg_class where oid='public.profiles'::regclass),'profiles RLS enabled');
select ok(not exists(select 1 from pg_policy where polrelid='public.profiles'::regclass and 0=any(polroles)),'profiles has no policy for PUBLIC');
select ok((select count(*)>0 from public.profiles),'profiles contains fixtures visible to trusted owner');
set local role anon;
select throws_ok('select * from public.countries', '42501', null, 'anon has no SELECT grant on countries');
select ok(not has_table_privilege(current_user,'public.countries','INSERT'),'anon has no INSERT on countries');
select ok(not has_table_privilege(current_user,'public.countries','UPDATE'),'anon has no UPDATE on countries');
select ok(not has_table_privilege(current_user,'public.countries','DELETE'),'anon has no DELETE on countries');
select ok(not has_table_privilege(current_user,'public.countries','TRUNCATE'),'anon has no TRUNCATE on countries');
select throws_ok('select * from public.administrative_areas', '42501', null, 'anon has no SELECT grant on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','INSERT'),'anon has no INSERT on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','UPDATE'),'anon has no UPDATE on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','DELETE'),'anon has no DELETE on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','TRUNCATE'),'anon has no TRUNCATE on administrative_areas');
select throws_ok('select * from public.organizations', '42501', null, 'anon has no SELECT grant on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','INSERT'),'anon has no INSERT on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','UPDATE'),'anon has no UPDATE on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','DELETE'),'anon has no DELETE on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','TRUNCATE'),'anon has no TRUNCATE on organizations');
select throws_ok('select * from public.profiles', '42501', null, 'anon has no SELECT grant on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','INSERT'),'anon has no INSERT on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','UPDATE'),'anon has no UPDATE on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','DELETE'),'anon has no DELETE on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','TRUNCATE'),'anon has no TRUNCATE on profiles');
reset role;
set local role authenticated;
select is((select count(*)::integer from public.countries),0,'authenticated without JWT identity cannot read countries');
select ok(not has_table_privilege(current_user,'public.countries','INSERT'),'authenticated has no INSERT on countries');
select ok(not has_table_privilege(current_user,'public.countries','UPDATE'),'authenticated has no UPDATE on countries');
select ok(not has_table_privilege(current_user,'public.countries','DELETE'),'authenticated has no DELETE on countries');
select ok(not has_table_privilege(current_user,'public.countries','TRUNCATE'),'authenticated has no TRUNCATE on countries');
select is((select count(*)::integer from public.administrative_areas),0,'authenticated without JWT identity cannot read administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','INSERT'),'authenticated has no INSERT on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','UPDATE'),'authenticated has no UPDATE on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','DELETE'),'authenticated has no DELETE on administrative_areas');
select ok(not has_table_privilege(current_user,'public.administrative_areas','TRUNCATE'),'authenticated has no TRUNCATE on administrative_areas');
select is((select count(*)::integer from public.organizations),0,'authenticated without JWT identity cannot read organizations');
select ok(not has_table_privilege(current_user,'public.organizations','INSERT'),'authenticated has no INSERT on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','UPDATE'),'authenticated has no UPDATE on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','DELETE'),'authenticated has no DELETE on organizations');
select ok(not has_table_privilege(current_user,'public.organizations','TRUNCATE'),'authenticated has no TRUNCATE on organizations');
select is((select count(*)::integer from public.profiles),0,'authenticated without JWT identity cannot read profiles');
select ok(not has_table_privilege(current_user,'public.profiles','INSERT'),'authenticated has no INSERT on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','UPDATE'),'authenticated has no UPDATE on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','DELETE'),'authenticated has no DELETE on profiles');
select ok(not has_table_privilege(current_user,'public.profiles','TRUNCATE'),'authenticated has no TRUNCATE on profiles');
reset role;
-- Temporary test-only grants prove RLS itself denies access even if a future
-- migration accidentally adds table privileges. ROLLBACK removes all grants.
grant select,insert,update,delete on public.countries,public.administrative_areas,public.organizations,public.profiles to anon,authenticated;
set local role anon;
select is((select count(*)::integer from public.countries),0,'RLS hides countries from anon');
select throws_ok($test$insert into public.countries(code,name) values ('XY','Denied')$test$,'42501',null,'RLS rejects anon insert into countries');
with changed as (update public.countries set active=active returning id) select is((select count(*)::integer from changed),0,'RLS prevents anon update of countries');
with removed as (delete from public.countries returning id) select is((select count(*)::integer from removed),0,'RLS prevents anon delete of countries');
select is((select count(*)::integer from public.administrative_areas),0,'RLS hides administrative_areas from anon');
select throws_ok($test$insert into public.administrative_areas(country_id,name,area_type) values ('10000000-0000-4000-8000-000000000001','Denied','REGION')$test$,'42501',null,'RLS rejects anon insert into administrative_areas');
with changed as (update public.administrative_areas set active=active returning id) select is((select count(*)::integer from changed),0,'RLS prevents anon update of administrative_areas');
with removed as (delete from public.administrative_areas returning id) select is((select count(*)::integer from removed),0,'RLS prevents anon delete of administrative_areas');
select is((select count(*)::integer from public.organizations),0,'RLS hides organizations from anon');
select throws_ok($test$insert into public.organizations(name,code,type) values ('Denied','DENIED','OTHER')$test$,'42501',null,'RLS rejects anon insert into organizations');
with changed as (update public.organizations set active=active returning id) select is((select count(*)::integer from changed),0,'RLS prevents anon update of organizations');
with removed as (delete from public.organizations returning id) select is((select count(*)::integer from removed),0,'RLS prevents anon delete of organizations');
select is((select count(*)::integer from public.profiles),0,'RLS hides profiles from anon');
select throws_ok($test$insert into public.profiles(id) values ('95000000-0000-4000-8000-000000000001')$test$,'42501',null,'RLS rejects anon insert into profiles');
with changed as (update public.profiles set display_name=display_name returning id) select is((select count(*)::integer from changed),0,'RLS prevents anon update of profiles');
with removed as (delete from public.profiles returning id) select is((select count(*)::integer from removed),0,'RLS prevents anon delete of profiles');
reset role;
set local role authenticated;
select is((select count(*)::integer from public.countries),0,'RLS hides countries from authenticated');
select throws_ok($test$insert into public.countries(code,name) values ('XY','Denied')$test$,'42501',null,'RLS rejects authenticated insert into countries');
with changed as (update public.countries set active=active returning id) select is((select count(*)::integer from changed),0,'RLS prevents authenticated update of countries');
with removed as (delete from public.countries returning id) select is((select count(*)::integer from removed),0,'RLS prevents authenticated delete of countries');
select is((select count(*)::integer from public.administrative_areas),0,'RLS hides administrative_areas from authenticated');
select throws_ok($test$insert into public.administrative_areas(country_id,name,area_type) values ('10000000-0000-4000-8000-000000000001','Denied','REGION')$test$,'42501',null,'RLS rejects authenticated insert into administrative_areas');
with changed as (update public.administrative_areas set active=active returning id) select is((select count(*)::integer from changed),0,'RLS prevents authenticated update of administrative_areas');
with removed as (delete from public.administrative_areas returning id) select is((select count(*)::integer from removed),0,'RLS prevents authenticated delete of administrative_areas');
select is((select count(*)::integer from public.organizations),0,'RLS hides organizations from authenticated');
select throws_ok($test$insert into public.organizations(name,code,type) values ('Denied','DENIED','OTHER')$test$,'42501',null,'RLS rejects authenticated insert into organizations');
with changed as (update public.organizations set active=active returning id) select is((select count(*)::integer from changed),0,'RLS prevents authenticated update of organizations');
with removed as (delete from public.organizations returning id) select is((select count(*)::integer from removed),0,'RLS prevents authenticated delete of organizations');
select is((select count(*)::integer from public.profiles),0,'RLS hides profiles from authenticated');
select throws_ok($test$insert into public.profiles(id) values ('95000000-0000-4000-8000-000000000001')$test$,'42501',null,'RLS rejects authenticated insert into profiles');
with changed as (update public.profiles set display_name=display_name returning id) select is((select count(*)::integer from changed),0,'RLS prevents authenticated update of profiles');
with removed as (delete from public.profiles returning id) select is((select count(*)::integer from removed),0,'RLS prevents authenticated delete of profiles');
reset role;
update public.profiles set account_status='PENDING_APPROVAL' where id='95000000-0000-4000-8000-000000000001';
set local role authenticated;
set local request.jwt.claims = '{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}';
select is((select count(*)::integer from public.profiles),0,'PENDING_APPROVAL cannot read even its own profile yet');
select is((select count(*)::integer from public.organizations),0,'PENDING_APPROVAL cannot read organizations yet');
reset role;
update public.profiles set account_status='ACTIVE' where id='95000000-0000-4000-8000-000000000001';
set local role authenticated;
set local request.jwt.claims = '{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}';
select is((select count(*)::integer from public.profiles),1,'ACTIVE can read own profile under M1.2');
select is((select count(*)::integer from public.organizations),0,'ACTIVE cannot read organizations yet');
reset role;
update public.profiles set account_status='SUSPENDED' where id='95000000-0000-4000-8000-000000000001';
set local role authenticated;
set local request.jwt.claims = '{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}';
select is((select count(*)::integer from public.profiles),0,'SUSPENDED cannot read even its own profile yet');
select is((select count(*)::integer from public.organizations),0,'SUSPENDED cannot read organizations yet');
reset role;
update public.profiles set account_status='REJECTED' where id='95000000-0000-4000-8000-000000000001';
set local role authenticated;
set local request.jwt.claims = '{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}';
select is((select count(*)::integer from public.profiles),0,'REJECTED cannot read even its own profile yet');
select is((select count(*)::integer from public.organizations),0,'REJECTED cannot read organizations yet');
reset role;
set local role service_role;
select is((select count(*)::integer from public.organizations where code='RLS-TEST'),1,'trusted service role can access backend data');
reset role;
select * from finish();
rollback;
