import type {Locale} from '../i18n';
const sl={
 title:'Podatki / Uvoz in izvoz',import:'Uvoz hidrantov',export:'Izvoz',template:'Predloga',history:'Zgodovina uvozov',profiles:'Preslikave',
 file:'Datoteka CSV, XLS ali XLSX',sheet:'Delovni list',delimiter:'Ločilo CSV',auto:'Samodejno',analyze:'Analiziraj datoteko',mapping:'Preslikava stolpcev',ignore:'Ni preslikano',
 organization:'Ciljna organizacija',name:'Ime',save:'Shrani',newProfile:'Nova preslikava',deactivate:'Deaktiviraj',activate:'Aktiviraj',profileName:'Ime preslikave',
 decimal:'Decimalno ločilo',point:'Pika',comma:'Vejica',clear:'Izrecno počisti prazne preslikane neobvezne celice',
 blankHelp:'Privzeto prazna neobvezna celica ohrani vrednost. Nepreslikana polja se nikoli ne spreminjajo. Počisti velja le za preslikana neobvezna polja.',
 preview:'Preveri celotno datoteko',previewTitle:'Predogled brez shranjevanja',row:'Vrstica',classification:'Razvrstitev',error:'Napaka',warning:'Opozorilo',before:'Obstoječa vrednost',after:'Predlagana vrednost',field:'Polje',
 selectValid:'Izberi veljavne',excludeWarnings:'Brez opozoril',creates:'Samo novi',updates:'Samo spremembe',none:'Počisti izbor',
 warnings:'Izrecno potrjujem izbrane vrstice z opozorili, vključno s sumljivimi koordinatami.',reason:'Razlog uvoza / spremembe stanja',confirm:'Potrdi in zamrzni uvoz',
 frozen:'Uvoz je zamrznjen. Ponovitev uporabi isti UUID in iste podatke.',apply:'Uporabi naslednji paket / nadaljuj',remaining:'Preostalo',
 partialHelp:'Paketi po največ 100 vrstic se potrdijo ločeno. Uspešne vrstice ostanejo shranjene tudi ob poznejši napaki. Konflikti in napake se ne uvozijo. Za popravke je potreben nov predogled.',
 refresh:'Osveži',previous:'Nazaj',next:'Naprej',details:'Podrobnosti',results:'Prenesi rezultate',errors:'Prenesi napake',resume:'Nadaljuj ta uvoz',
 filters:'Filtri',generated:'Ustvarjeno',language:'Jezik',instructions:'Navodila',
 templateHelp:'Za nove hidrante pustite UUID in oznako prazna. Organizacija in tip uporabljata kodo ali UUID iz Reference. Statusi so stabilne kode. Koordinate: decimalna pika, brez ločil tisočic. Obstoječih UUID, oznak in organizacije ni mogoče spreminjati.',
 limits:'Največ 10 MiB na datoteko, 16 listov, 10.000 podatkovnih vrstic, 64 stolpcev in 4.096 znakov na celico. Izvoz: 50.000 vrstic / 24 MiB podatkov. Večji obseg omejite s filtri.',
 selected:'Izbrano',empty:'Ni podatkov',loading:'Obdelava …',reset:'Nov uvoz',map:'Predogled lokacij',mapMissing:'Zemljevid ni na voljo; uporabite preglednico.',
 readOnly:'Uvoz je dovoljen le za organizacije, kjer imate neposredno vlogo vodje ali administratorja. Podedovani dostop omogoča izvoz.',
 code:'Oznaka',version:'Različica',all:'Vse',statusMap:'Preslikava stanj',typeMap:'Preslikava tipov',source:'Izvorna vrednost',target:'Ciljna vrednost',
 profileHelp:'Preslikava shrani le nastavitve stolpcev in vrednosti, ne vrstic ali datoteke.',
 hydrants:'Hidranti',inspections:'Pregledi',teams:'Ekipe',plans:'Načrti',from:'Od datuma pregleda',to:'Do datuma pregleda (izključno)',
 codes:{CREATE:'Nov hidrant',UPDATE:'Sprememba',UNCHANGED:'Nespremenjeno',SKIP:'Preskočeno',WARNING:'Opozorilo',CONFLICT:'Konflikt',ERROR:'Napaka',PENDING:'Čaka',WORKING:'Deluje',NOT_WORKING:'Ne deluje',NEEDS_INSPECTION:'Potrebuje pregled',UNKNOWN:'Neznano',
 INVALID_FILE:'Neveljavna ali nepodprta datoteka.',INVALID_CSV:'Neveljaven zapis CSV.',LIMIT_EXCEEDED:'Presežena omejitev datoteke ali obdelave.',EXPORT_LIMIT:'Izvoz presega omejitev. Zožite filtre; delni izvoz ni ustvarjen.',BUSY:'Obdelava je zasedena. Poskusite znova.',DELIMITER_REQUIRED:'Ločila ni mogoče zanesljivo določiti. Izberite ga ročno.',ENCRYPTED_FILE:'Šifrirane datoteke niso podprte.',FORMULA_VALUE_MISSING:'Formula nima uporabne shranjene vrednosti. Izvozite vrednosti brez formul.',INVALID_CELL:'Neveljavna vrednost celice.',INVALID_MAPPING:'Neveljavna ali podvojena preslikava stolpcev.',INVALID_FIELDS:'Preverite obvezna polja, koordinate in vrednosti.',INVALID_NUMBER:'Neveljavno število ali preveč decimalnih mest.',AMBIGUOUS_NUMBER:'Dvoumno število. Izberite decimalno ločilo.',INVALID_STATUS:'Izberite veljavno stanje.',INVALID_TYPE:'Izberite veljaven aktiven tip.',DUPLICATE_IDENTITY:'Več vrstic se nanaša na isti hidrant.',NOT_AUTHORIZED_OR_INVALID_TARGET:'Nedovoljen ali neveljaven cilj.',NOT_AUTHORIZED:'Dostop ni več dovoljen. Ponovno odprite organizacijo.',STALE_VERSION:'Hidrant je bil spremenjen. Ustvarite nov predogled.',SUSPICIOUS_COORDINATES:'Koordinate (0, 0) so sumljive. Preverite lokacijo.',NO_COORDINATES:'Hidrant nima koordinat in ni prikazan na zemljevidu.',OPERATION_REUSED:'UUID operacije je že vezan na druge podatke.',WARNINGS_REQUIRE_CONFIRMATION:'Opozorila zahtevajo izrecno potrditev.',EXPECTED_VERSION_REQUIRED:'Manjka različica predogleda.',INVALID_IMPORT:'Neveljaven uvoz.',INVALID_PROFILE:'Neveljavna preslikava.',INVALID_QUERY:'Neveljavna poizvedba.',REQUEST_FAILED:'Zahteva ni uspela. Ohranite ta zaslon in poskusite znova.'} as Record<string,string>,
 fields:{uuid:'UUID',code:'Oznaka hidranta',organization:'Organizacija',type:'Tip',status:'Stanje',latitude:'Zemljepisna širina',longitude:'Zemljepisna dolžina',address:'Naslov',location_description:'Opis lokacije',notes:'Opombe',inspection_interval_months:'Interval pregledov (meseci)',active:'Aktiven',hydrant_type_id:'Tip (UUID)'} as Record<string,string>
};
const de:typeof sl={
 title:'Daten / Import und Export',import:'Hydranten importieren',export:'Export',template:'Vorlage',history:'Importverlauf',profiles:'Zuordnungen',file:'CSV-, XLS- oder XLSX-Datei',sheet:'Arbeitsblatt',delimiter:'CSV-Trennzeichen',auto:'Automatisch',analyze:'Datei analysieren',mapping:'Spaltenzuordnung',ignore:'Nicht zugeordnet',organization:'Zielorganisation',name:'Name',save:'Speichern',newProfile:'Neue Zuordnung',deactivate:'Deaktivieren',activate:'Aktivieren',profileName:'Name der Zuordnung',decimal:'Dezimaltrennzeichen',point:'Punkt',comma:'Komma',clear:'Leere zugeordnete optionale Zellen ausdrücklich löschen',
 blankHelp:'Leere optionale Zellen behalten standardmäßig den bisherigen Wert. Nicht zugeordnete Felder bleiben unverändert. Löschen gilt nur für zugeordnete optionale Felder.',
 preview:'Gesamte Datei prüfen',previewTitle:'Vorschau ohne Speicherung',row:'Zeile',classification:'Klassifizierung',error:'Fehler',warning:'Warnung',before:'Bisheriger Wert',after:'Vorgeschlagener Wert',field:'Feld',selectValid:'Gültige auswählen',excludeWarnings:'Ohne Warnungen',creates:'Nur neue',updates:'Nur Änderungen',none:'Auswahl leeren',warnings:'Ich bestätige ausdrücklich ausgewählte Warnungen einschließlich auffälliger Koordinaten.',reason:'Importgrund / Grund der Statusänderung',confirm:'Import bestätigen und festschreiben',frozen:'Import festgeschrieben. Wiederholungen verwenden dieselbe UUID und dieselben Daten.',apply:'Nächstes Paket anwenden / fortsetzen',remaining:'Verbleibend',
 partialHelp:'Pakete mit höchstens 100 Zeilen werden einzeln bestätigt. Erfolgreiche Zeilen bleiben bei späteren Fehlern gespeichert. Konflikte und Fehler werden nicht importiert. Korrekturen benötigen eine neue Vorschau.',
 refresh:'Aktualisieren',previous:'Zurück',next:'Weiter',details:'Details',results:'Ergebnisse herunterladen',errors:'Fehler herunterladen',resume:'Diesen Import fortsetzen',filters:'Filter',generated:'Erstellt',language:'Sprache',instructions:'Anleitung',templateHelp:'Für neue Hydranten UUID und Kennung leer lassen. Organisation und Typ verwenden Codes oder UUIDs aus Reference. Statuswerte sind stabile Codes. Koordinaten: Dezimalpunkt ohne Tausendertrennzeichen. Bestehende UUID, Kennung und Organisation sind unveränderlich.',limits:'Höchstens 10 MiB pro Datei, 16 Blätter, 10.000 Datenzeilen, 64 Spalten und 4.096 Zeichen pro Zelle. Export: 50.000 Zeilen / 24 MiB Daten. Größere Bereiche mit Filtern eingrenzen.',selected:'Ausgewählt',empty:'Keine Daten',loading:'Verarbeitung …',reset:'Neuer Import',map:'Standortvorschau',mapMissing:'Karte nicht verfügbar; verwenden Sie die Tabelle.',readOnly:'Import nur mit direkter Manager- oder Administratorrolle in der Zielorganisation. Geerbter Zugriff erlaubt Export.',code:'Kennung',version:'Version',all:'Alle',statusMap:'Statuszuordnung',typeMap:'Typzuordnung',source:'Quellwert',target:'Zielwert',profileHelp:'Zuordnungen speichern nur Spalten- und Werteinstellungen, keine Zeilen oder Dateien.',hydrants:'Hydranten',inspections:'Prüfungen',teams:'Teams',plans:'Pläne',from:'Prüfdatum ab',to:'Prüfdatum bis (ausschließlich)',
 codes:{CREATE:'Neuer Hydrant',UPDATE:'Änderung',UNCHANGED:'Unverändert',SKIP:'Übersprungen',WARNING:'Warnung',CONFLICT:'Konflikt',ERROR:'Fehler',PENDING:'Ausstehend',WORKING:'Funktionsfähig',NOT_WORKING:'Nicht funktionsfähig',NEEDS_INSPECTION:'Prüfung erforderlich',UNKNOWN:'Unbekannt',INVALID_FILE:'Ungültige oder nicht unterstützte Datei.',INVALID_CSV:'Ungültiges CSV-Format.',LIMIT_EXCEEDED:'Datei- oder Verarbeitungslimit überschritten.',EXPORT_LIMIT:'Exportlimit überschritten. Filter eingrenzen; kein unvollständiger Export wurde erstellt.',BUSY:'Verarbeitung ausgelastet. Erneut versuchen.',DELIMITER_REQUIRED:'Trennzeichen nicht eindeutig. Bitte manuell wählen.',ENCRYPTED_FILE:'Verschlüsselte Dateien werden nicht unterstützt.',FORMULA_VALUE_MISSING:'Formel ohne gespeicherten Wert. Werte ohne Formeln exportieren.',INVALID_CELL:'Ungültiger Zellenwert.',INVALID_MAPPING:'Ungültige oder doppelte Spaltenzuordnung.',INVALID_FIELDS:'Pflichtfelder, Koordinaten und Werte prüfen.',INVALID_NUMBER:'Ungültige Zahl oder zu viele Dezimalstellen.',AMBIGUOUS_NUMBER:'Mehrdeutige Zahl. Dezimaltrennzeichen wählen.',INVALID_STATUS:'Gültigen Status auswählen.',INVALID_TYPE:'Gültigen aktiven Typ auswählen.',DUPLICATE_IDENTITY:'Mehrere Zeilen beziehen sich auf denselben Hydranten.',NOT_AUTHORIZED_OR_INVALID_TARGET:'Nicht erlaubtes oder ungültiges Ziel.',NOT_AUTHORIZED:'Zugriff nicht mehr erlaubt. Organisation erneut öffnen.',STALE_VERSION:'Hydrant wurde geändert. Neue Vorschau erstellen.',SUSPICIOUS_COORDINATES:'Koordinaten (0, 0) sind auffällig. Standort prüfen.',NO_COORDINATES:'Hydrant ohne Koordinaten; nicht auf der Karte dargestellt.',OPERATION_REUSED:'Operations-UUID gehört bereits zu anderen Daten.',WARNINGS_REQUIRE_CONFIRMATION:'Warnungen müssen ausdrücklich bestätigt werden.',EXPECTED_VERSION_REQUIRED:'Vorschauversion fehlt.',INVALID_IMPORT:'Ungültiger Import.',INVALID_PROFILE:'Ungültige Zuordnung.',INVALID_QUERY:'Ungültige Abfrage.',REQUEST_FAILED:'Anfrage fehlgeschlagen. Diesen Bildschirm behalten und erneut versuchen.'},
 fields:{uuid:'UUID',code:'Hydrantenkennung',organization:'Organisation',type:'Typ',status:'Status',latitude:'Breitengrad',longitude:'Längengrad',address:'Adresse',location_description:'Standortbeschreibung',notes:'Notizen',inspection_interval_months:'Prüfintervall (Monate)',active:'Aktiv',hydrant_type_id:'Typ (UUID)'}
};
export const exchangeText=(locale:Locale)=>locale==='de'?de:sl;
