import test from 'node:test';
import assert from 'node:assert/strict';
import { defaultFilters, parseFilters, queryString, matches, roleFilters } from '../lib/hydrants/query.ts';
import { RegistryController } from '../lib/hydrants/controller.ts';
import { hydrantService } from '../lib/hydrants/service.ts';
import { RegistryError } from '../lib/hydrants/domain.ts';
const org='11111111-1111-4111-8111-111111111111',type='22222222-2222-4222-8222-222222222222',cursor='33333333-3333-4333-8333-333333333333';
const row={id:cursor,organization_id:org,code:'ORG-H-000001',hydrant_type_id:type,address:'Celovška 100%_',location_description:'North "gate", (east)',status:'NOT_WORKING',active:true,version:2};
const state=(overrides={})=>({...defaultFilters(),...overrides});
for(const [label,search] of [['code','org-h-000001'],['address','CELOVŠKA'],['description','north "gate"'],['literal special characters','%_'],['trimmed',' Celovška '],['blank',' \t ']])test('query semantics '+label,()=>assert.equal(matches(row,state({search})),true));
test('percent and underscore never act as wildcards',()=>{assert.equal(matches(row,state({search:'Cel%ka'})),false);assert.equal(matches(row,state({search:'N_rth'})),false)});
test('AND combines type status active and OR text fields',()=>{assert.equal(matches(row,state({search:'gate',typeId:type,status:'NOT_WORKING'})),true);assert.equal(matches(row,state({search:'gate',typeId:type,status:'WORKING'})),false);assert.equal(matches(row,state({typeId:cursor})),false);assert.equal(matches(row,state({active:'inactive'})),false);assert.equal(matches({...row,active:false},state({active:'all'})),true)});
test('URL query roundtrip safely encodes punctuation and cursor',()=>{const f=state({search:'%_ "x", &?',typeId:type,status:'UNKNOWN',active:'inactive',after:cursor});const p=new URLSearchParams(queryString(org,f));assert.equal(p.get('org'),org);assert.deepEqual(parseFilters(Object.fromEntries(p)),f)});
test('invalid URL statuses types pages cursors arrays and active values safely default',()=>{const q=parseFilters({q:['a','b'],status:'BROKEN',type:'x),or(id.gt.0',after:'bad',active:'false OR true',page:'-Infinity'});assert.deepEqual(q,{search:'',active:'active',typeId:undefined,status:undefined,after:undefined})});
test('search length is bounded and blank search normalized',()=>{assert.equal(parseFilters({q:'  x  '}).search,'x');assert.equal(parseFilters({q:'x'.repeat(300)}).search.length,200);assert.equal(parseFilters({q:' \n\t '}).search,'')});
test('firefighter query state always active; manager/admin allow all three states',()=>{assert.equal(roleFilters(state({active:'inactive'}),'FIREFIGHTER').active,'active');for(const role of ['MANAGER','ADMIN'])for(const active of ['active','inactive','all'])assert.equal(roleFilters(state({active}),role).active,active)});
function fixture(mode='list',filters=state()) {
 const calls=[];let current={...row};let fail=false;
 const service={organizations:async()=>[{id:org,name:'A',active:true,role:'MANAGER'},{id:cursor,name:'B',active:true,role:'FIREFIGHTER'}],types:async id=>[{id:type,organization_id:id,name:'Dynamic',active:true}],list:async q=>{calls.push(q);return current.organization_id===q.organizationId&&matches(current,q)?[current]:[]},get:async()=>current,status:async(o,id,status,version)=>{assert.equal(version,current.version);if(fail){current={...current,address:'Server new',version:version+1};throw new RegistryError('conflict')};current={...current,status,version:version+1};return current},active:async(o,id,active)=>current={...current,active,version:current.version+1},update:async()=>{current={...current,version:3};throw new RegistryError('conflict')}};
 return {c:new RegistryController(service,mode,mode==='list'?undefined:row.id,org,filters),calls,service,conflict:()=>fail=true};
}
for(const [key,value] of [['search','Celovška'],['typeId',type],['status','WORKING'],['active','inactive']])test(key+' change resets cursor and reloads server query',async()=>{const f=fixture('list',state({after:cursor}));await f.c.load();await f.c.applyFilters({...f.c.snapshot().filters,[key]:value});assert.equal(f.calls.at(-1).after,undefined);assert.equal(f.calls.at(-1)[key],value)});
test('clear resets combined query and organization change resets roles/types/query',async()=>{const f=fixture();await f.c.load();await f.c.applyFilters(state({search:'absent',typeId:type,status:'WORKING',active:'all'}));assert.equal(f.c.snapshot().rows.length,0);await f.c.applyFilters(defaultFilters());assert.equal(f.c.snapshot().rows.length,1);await f.c.switchOrganization(cursor);assert.deepEqual(f.c.snapshot().filters,defaultFilters());assert.equal(f.c.snapshot().org.role,'FIREFIGHTER');assert.equal(f.c.snapshot().types[0].organization_id,cursor)});
test('status mutation is absent from the preserved filter on returning to list',async()=>{const f=fixture('detail',state({status:'NOT_WORKING'}));await f.c.load();await f.c.status('WORKING');assert.equal(matches(f.c.snapshot().selected,f.c.snapshot().filters),false);const back=new RegistryController(f.service,'list',undefined,org,f.c.snapshot().filters);await back.load();assert.equal(back.snapshot().rows.length,0)});
test('deactivation leaves active-only and appears in inactive-only result',async()=>{const f=fixture('detail');await f.c.load();await f.c.requestActive();await f.c.confirm();assert.equal(matches(f.c.snapshot().selected,f.c.snapshot().filters),false);const back=new RegistryController(f.service,'list',undefined,org,state({active:'inactive'}));await back.load();assert.equal(back.snapshot().rows.length,1)});
test('conflict retains filters and requires explicit draft review',async()=>{const f=fixture('edit',state({search:'Celovška',status:'NOT_WORKING'}));await f.c.load();f.c.change({...f.c.snapshot().draft,notes:'retained'});await f.c.save();assert.equal(f.c.snapshot().conflict,true);assert.equal(f.c.snapshot().draft.notes,'retained');assert.equal(f.c.snapshot().draft.version,2);assert.equal(f.c.snapshot().filters.search,'Celovška');f.c.review();assert.equal(f.c.snapshot().draft.version,3)});
test('query transport is one bounded RPC with literal parameters and no client registry download',async()=>{let calls=[];const service=hydrantService({rpc:async(name,args)=>{calls.push([name,args]);return {data:[],error:null}},from:()=>{throw Error('must not download registry')}});await service.list({organizationId:org,search:' %_\"(), ',typeId:type,status:'NOT_WORKING',active:'all',after:cursor});assert.deepEqual(calls,[['search_hydrants',{organization:org,search_text:'%_"(),',type_id:type,status_filter:'NOT_WORKING',active_filter:'all',after_id:cursor,page_size:50}]])});
