import test from 'node:test';
import assert from 'node:assert/strict';
import { RegistryController } from '../lib/hydrants/controller.ts';
import { fields, emptyDraft, payload, RegistryError } from '../lib/hydrants/domain.ts';
import { apiError, hydrantService } from '../lib/hydrants/service.ts';
const h = { id:'h', organization_id:'a', code:'A-H-000001', hydrant_type_id:'type', status:'WORKING', latitude:null, longitude:null, address:'Street', location_description:null, notes:null, inspection_interval_months:null, active:true, version:2, created_by:'user' };
function fixture(mode='list', role='MANAGER') {
  const calls=[];
  const service = {
    organizations: async()=>[{id:'a',name:'A',active:true,role},{id:'b',name:'B',active:true,role:'FIREFIGHTER'}],
    types:async org=>[{id:org==='a'?'type':'other',name:'Custom',code:'CUSTOM',active:true,organization_id:org}],
    list:async(q)=>{calls.push(['list',q.organizationId,q.active,q.after]);return q.organizationId==='a'?[{...h}]:[]},
    get:async(org,id)=>({...h,organization_id:org,id}),
    create:async(...args)=>{calls.push(['create',...args]);return {...h,id:args[1]}},
    update:async(...args)=>{calls.push(['update',...args]);return {...h,version:3}},
    status:async(...args)=>{calls.push(['status',...args]);return {...h,status:args[2],version:3}},
    active:async(...args)=>{calls.push(['active',...args]);return {...h,active:args[2],version:3}},
  };
  return {service,calls,c:new RegistryController(service,mode,['detail','edit'].includes(mode)?'h':undefined)};
}
const valid=()=>({...emptyDraft('stable'),type:'type',address:' Street '});
test('registry loading, content and explicit automatic organization',async()=>{const {c}=fixture();assert.equal(c.snapshot().loading,true);await c.load();assert.equal(c.snapshot().loading,false);assert.equal(c.snapshot().org.id,'a');assert.equal(c.snapshot().rows[0].code,h.code)});
test('registry empty content',async()=>{const {c,service}=fixture();service.list=async()=>[];await c.load();assert.deepEqual(c.snapshot().rows,[]);assert.equal(c.snapshot().error,undefined)});
test('network read clears stale rows; refresh recovers',async()=>{const {c,service}=fixture();await c.load();service.list=async()=>{throw new TypeError('fetch failed')};await c.load();assert.equal(c.snapshot().error,'network');assert.deepEqual(c.snapshot().rows,[]);service.list=async()=>[h];await c.load();assert.equal(c.snapshot().error,undefined);assert.equal(c.snapshot().rows.length,1)});
test('switch clears hydrants, type and manager capabilities',async()=>{const {c}=fixture();await c.load();await c.applyFilters({search:'',active:'all'});await c.switchOrganization('b');assert.equal(c.snapshot().org.role,'FIREFIGHTER');assert.equal(c.snapshot().types[0].id,'other');assert.deepEqual(c.snapshot().rows,[]);assert.equal(c.snapshot().filters.active,'active')});
test('unknown organization fails closed',async()=>{const {c}=fixture();await c.load('foreign');assert.equal(c.snapshot().error,'forbidden');assert.equal(c.snapshot().org,undefined)});
test('pagination uses last UUID and replaces bounded page',async()=>{const {c,service,calls}=fixture();service.list=async(q)=>{calls.push(['list',q.organizationId,q.active,q.after]);return q.after?[{...h,id:'50'}]:Array.from({length:50},(_,i)=>({...h,id:String(i)}))};await c.load();assert.equal(c.snapshot().more,true);await c.more();assert.equal(c.snapshot().rows.length,1);assert.equal(calls.at(-1)[3],'49');assert.equal(c.snapshot().more,false)});
for(const role of ['FIREFIGHTER','MANAGER','ADMIN']) test(role+' creates with stable UUID and server code',async()=>{const {c,calls}=fixture('new',role);await c.load();const draft=c.snapshot().draft;c.change({...draft,type:'type',address:'Street'});await c.save();assert.equal(calls[0][0],'create');assert.equal(calls[0][2],draft.id);assert.equal(c.snapshot().saved.code,h.code)});
for(const role of ['MANAGER','ADMIN']) test(role+' edits with baseline version',async()=>{const {c,calls}=fixture('edit',role);await c.load();c.change({...c.snapshot().draft,notes:'updated'});await c.save();assert.equal(calls[0][0],'update');assert.equal(calls[0][4],2)});
test('firefighter direct edit route has no draft or edit action',async()=>{const {c,calls}=fixture('edit','FIREFIGHTER');await c.load();assert.equal(c.snapshot().error,'forbidden');await c.save();assert.equal(calls.length,0)});
test('firefighter cannot include inactive or deactivate',async()=>{const {c,calls}=fixture('detail','FIREFIGHTER');await c.load();await c.applyFilters({search:'',active:'all'});await c.requestActive();await c.confirm();assert.equal(c.snapshot().filters.active,'active');assert.equal(c.snapshot().confirm,false);assert.equal(calls.length,0)});
test('deactivation needs confirmation; cancel has no mutation; reactivation keeps identity',async()=>{const {c,calls}=fixture('detail');await c.load();await c.requestActive();assert.equal(calls.length,0);assert.equal(c.snapshot().confirm,true);c.dismiss();await c.confirm();assert.equal(calls.length,0);await c.requestActive();await c.confirm();assert.deepEqual(calls[0],['active','a','h',false,2]);assert.equal(c.snapshot().selected.active,false);await c.requestActive();assert.deepEqual(calls[1],['active','a','h',true,3]);assert.equal(c.snapshot().selected.code,h.code)});
test('status narrow mutation supplies version',async()=>{const {c,calls}=fixture('detail','FIREFIGHTER');await c.load();await c.status('NOT_WORKING');assert.deepEqual(calls[0],['status','a','h','NOT_WORKING',2]);assert.equal(c.snapshot().selected.version,3)});
test('create duplicate submissions blocked synchronously',async()=>{const {c,service}=fixture('new');await c.load();c.change({...c.snapshot().draft,type:'type',address:'Street'});let finish;let count=0;service.create=()=>{count++;return new Promise(r=>finish=r)};const first=c.save();await c.save();assert.equal(count,1);assert.equal(c.snapshot().busy,true);finish(h);await first;await c.save();assert.equal(count,1)});
test('uncertain create failure preserves draft UUID on explicit retry',async()=>{const {c,service}=fixture('new');await c.load();const id=c.snapshot().draft.id;c.change({...c.snapshot().draft,type:'type',address:'Street'});let ids=[];service.create=async(org,id)=>{ids.push(id);if(ids.length===1)throw new TypeError('network');return h};await c.save();assert.equal(c.snapshot().draft.id,id);await c.save();assert.deepEqual(ids,[id,id])});
test('missing location rejected before create',async()=>{const {c,calls}=fixture('new');await c.load();c.change({...c.snapshot().draft,type:'type'});await c.save();assert.equal(c.snapshot().error,'location');assert.equal(calls.length,0)});
test('conflict keeps draft and demands explicit review before retry at fresh version',async()=>{const {c,service,calls}=fixture('edit');await c.load();c.change({...c.snapshot().draft,notes:'my notes'});service.update=async(...args)=>{calls.push(args);if(calls.length===1)throw new RegistryError('conflict');return {...h,version:5}};service.get=async()=>({...h,notes:'their notes',version:4});await c.save();assert.equal(c.snapshot().selected.notes,'their notes');assert.equal(c.snapshot().draft.notes,'my notes');assert.equal(c.snapshot().draft.version,2);await c.save();assert.equal(calls.length,1);c.review();await c.save();assert.equal(calls[1][3],4)});
test('failed conflict reload disables save until refresh and review',async()=>{const {c,service}=fixture('edit');await c.load();service.update=async()=>{throw new RegistryError('conflict')};service.get=async()=>{throw new TypeError('fetch')};await c.save();assert.equal(c.snapshot().selected,undefined);c.review();assert.equal(c.snapshot().reviewed,false);service.get=async()=>({...h,version:4});await c.load();assert.equal(c.snapshot().selected.version,4);assert.equal(c.snapshot().draft.version,2);c.review();assert.equal(c.snapshot().draft.version,4)});
test('status conflict reloads latest without replay',async()=>{const {c,service}=fixture('detail');await c.load();let count=0;service.status=async()=>{count++;throw new RegistryError('conflict')};service.get=async()=>({...h,version:7,status:'UNKNOWN'});await c.status('NOT_WORKING');assert.equal(count,1);assert.equal(c.snapshot().selected.version,7);assert.equal(c.snapshot().conflict,true)});
test('refresh during edit never silently advances edit baseline',async()=>{const {c,service}=fixture('edit');await c.load();service.get=async()=>({...h,version:8});await c.load();assert.equal(c.snapshot().draft.version,2)});
test('revocation clears protected state and draft',async()=>{const {c,service}=fixture('edit');await c.load();service.update=async()=>{throw new RegistryError('forbidden')};await c.save();assert.equal(c.snapshot().draft,undefined);assert.equal(c.snapshot().selected,undefined);assert.equal(c.snapshot().org,undefined)});
test('signout ignores an in-flight response',async()=>{const {c,service}=fixture();let finish;service.organizations=()=>new Promise(r=>finish=r);const pending=c.load();c.clear();finish([{id:'a',role:'ADMIN',active:true}]);await pending;assert.equal(c.snapshot().org,undefined);assert.equal(c.snapshot().error,'expired')});
test('inactive organization is read-only',async()=>{const {c,service,calls}=fixture('detail');service.organizations=async()=>[{id:'a',role:'ADMIN',active:false}];await c.load();await c.status('UNKNOWN');await c.requestActive();assert.equal(calls.length,0)});
test('active type must be dynamic or retained historical type',async()=>{const {c,service,calls}=fixture('edit');service.types=async()=>[];await c.load();await c.save();assert.equal(calls.length,1);const f=fixture('new');await f.c.load();f.c.change({...f.c.snapshot().draft,type:'inactive',address:'Street'});await f.c.save();assert.equal(f.c.snapshot().error,'type')});
for(const [name,change,reason] of [
 ['blank location',{address:'   ',description:'\t'},'location'],['coordinate pair',{latitude:'1'},'coordinates'],['latitude bounds',{latitude:'91',longitude:'1'},'coordinates'],['longitude bounds',{latitude:'1',longitude:'181'},'coordinates'],['nonfinite',{latitude:'Infinity',longitude:'1'},'coordinates'],['hexadecimal',{latitude:'0x10',longitude:'1'},'coordinates'],['negative interval',{interval:'-1'},'interval'],['fractional interval',{interval:'1.5'},'interval'],['overflow interval',{interval:'2147483648'},'interval'],['missing type',{type:''},'type']
]) test('validation '+name,()=>assert.throws(()=>fields({...valid(),...change}),e=>e.reason===reason));
test('coordinate boundary and decimal comma accepted with optional blank values',()=>{const f=fields({...valid(),latitude:'-90',longitude:'180',notes:'  '});assert.equal(f.latitude,-90);assert.equal(f.longitude,180);assert.equal(f.notes,null);assert.equal(fields({...valid(),latitude:'46,1',longitude:'14,2'}).latitude,46.1)});
test('payloads exclude metadata and separate create status from master edit',()=>{const f=fields(valid());assert.deepEqual(Object.keys(payload(f,true)).sort(),['latitude','longitude','address','location_description','notes','inspection_interval_months','status'].sort());assert.equal('status' in payload(f,false),false);assert.equal(payload(f,false).hydrant_type_id,'type')});
for(const [error,status,expected] of [[{code:'PGRST301'},401,'expired'],[{code:'42501'},403,'forbidden'],[{code:'23514'},400,'validation'],[{code:'P0001',message:'HYDRANT_VERSION_CONFLICT'},400,'conflict'],[{message:'Failed to fetch'},0,'network'],[{code:'P0001',message:'secret SQL detail'},500,'server']]) test('safe API category '+expected,()=>assert.equal(apiError(error,status).message,expected));
function clientFixture() {
 const queries=[],rpcs=[];let rows=[];
 const client={auth:{getUser:async()=>({data:{user:{id:'user'}},error:null})},from(table){const args=[table];queries.push(args);const q={select:v=>(args.push(['select',v]),q),eq:(...v)=>(args.push(['eq',...v]),q),is:(...v)=>(args.push(['is',...v]),q),order:v=>(args.push(['order',v]),q),limit:v=>(args.push(['limit',v]),q),gt:(...v)=>(args.push(['gt',...v]),q),then:resolve=>Promise.resolve({data:rows,error:null}).then(resolve)};return q},rpc:async(name,args)=>{rpcs.push([name,args]);return {data:h,error:null}}};
 return {client,queries,rpcs,setRows:r=>rows=r,service:hydrantService(client)};
}
test('service uses four narrow RPCs with exact parameter allowlists',async()=>{const f=clientFixture(),data=fields(valid());await f.service.create('a','stable',data);await f.service.status('a','h','UNKNOWN',2);await f.service.update('a','h',data,3);await f.service.active('a','h',false,4);assert.deepEqual(f.rpcs.map(r=>r[0]),['create_hydrant','change_hydrant_status','update_hydrant','set_hydrant_active']);assert.deepEqual(f.rpcs[0][1],{organization:'a',hydrant_id:'stable',hydrant_type:'type',fields:payload(data,true)});assert.deepEqual(f.rpcs[1][1],{organization:'a',hydrant_id:'h',new_status:'UNKNOWN',expected_version:2});assert.deepEqual(f.rpcs[2][1],{organization:'a',hydrant_id:'h',changes:payload(data,false),expected_version:3});assert.deepEqual(f.rpcs[3][1],{organization:'a',hydrant_id:'h',is_active:false,expected_version:4})});
test('uncertain creation reconciles readable own UUID without RPC',async()=>{const f=clientFixture();f.setRows([h]);assert.equal((await f.service.create('a','h',fields(valid()))).code,h.code);assert.equal(f.rpcs.length,0);assert.ok(f.queries[0].some(v=>JSON.stringify(v)==='["eq","organization_id","a"]'))});
test('foreign creator collision is rejected without RPC',async()=>{const f=clientFixture();f.setRows([{...h,created_by:'other'}]);await assert.rejects(f.service.create('a','h',fields(valid())),e=>e.reason==='forbidden');assert.equal(f.rpcs.length,0)});
test('scoped bounded reads and cursor use existing RLS',async()=>{const f=clientFixture();await f.service.list({organizationId:'a',search:'',active:'active',after:'cursor'});assert.deepEqual(f.rpcs[0],['search_hydrants',{organization:'a',search_text:'',type_id:null,status_filter:null,active_filter:'active',after_id:'cursor',page_size:50}]);await assert.rejects(f.service.get('b','missing'),e=>e.reason==='unavailable')});
test('metadata pagination retains own roles beyond first 100 memberships',async()=>{
 const calls=[];const memberships=Array.from({length:101},(_,i)=>({organization_id:String(i).padStart(3,'0'),role:i===100?'MANAGER':'FIREFIGHTER'}));
 const organizations=memberships.map(m=>({id:m.organization_id,name:m.organization_id,active:true}));
 const client={auth:{getUser:async()=>({data:{user:{id:'me'}},error:null})},rpc:async()=>({data:'ACTIVE',error:null}),from(table){let after;const filters=[];const q={select:()=>q,order:()=>q,limit:n=>{assert.equal(n,100);return q},eq:(k,v)=>{filters.push([k,v]);return q},gt:(k,v)=>{after=v;return q},then:resolve=>{calls.push([table,filters,after]);const all=table==='user_organizations'?memberships:organizations;return Promise.resolve({data:all.filter(r=>(r.id??r.organization_id)>(after??'')).slice(0,100),error:null}).then(resolve)}};return q}};
 const result=await hydrantService(client).organizations();assert.equal(result.length,101);assert.equal(result.at(-1).role,'MANAGER');const own=calls.filter(c=>c[0]==='user_organizations');assert.equal(own.length,2);assert.deepEqual(own[1][1],[['user_id','me']]);assert.equal(own[1][2],'099');
});
test('service missing session is expired',async()=>{const f=clientFixture();f.client.auth.getUser=async()=>({data:{user:null},error:{status:400}});await assert.rejects(f.service.organizations(),e=>e.reason==='expired')});
test('role loss on refresh removes edit draft',async()=>{const {c,service}=fixture('edit');await c.load();service.organizations=async()=>[{id:'a',active:true,role:'FIREFIGHTER'}];await c.load();assert.equal(c.snapshot().draft,undefined);assert.equal(c.snapshot().error,'forbidden')});
test('deactivation conflict closes confirmation and reloads current server state',async()=>{const {c,service}=fixture('detail');await c.load();service.active=async()=>{throw new RegistryError('conflict')};service.get=async()=>({...h,active:false,version:3});await c.requestActive();await c.confirm();assert.equal(c.snapshot().confirm,false);assert.equal(c.snapshot().selected.active,false);assert.equal(c.snapshot().conflict,true)});
