package si.gasilko.app.feature.hydrants

import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.*
import org.junit.Assert.*
import org.junit.Test
import si.gasilko.app.feature.hydrants.domain.*
import si.gasilko.app.feature.hydrants.presentation.*

@OptIn(ExperimentalCoroutinesApi::class)
class HydrantViewModelTest {
    private class Fake(var role: RegistryRole = RegistryRole.MANAGER): HydrantRepository {
        var row=Hydrant("h","a","A-H-000001","t",HydrantStatus.UNKNOWN,address="Original",version=2)
        var fail: RegistryError?=null;var conflict=false;var empty=false;var calls=0;var suppliedVersion=0L;var lastOrg=""
        var gate: CompletableDeferred<Unit>?=null
        override suspend fun organizations(): List<RegistryOrganization> { fail?.let { throw RegistryFailure(it) };return listOf(RegistryOrganization("a","A",role),RegistryOrganization("b","B",RegistryRole.FIREFIGHTER)) }
        override suspend fun types(organization: String)=listOf(HydrantType("t",null,"CUSTOM","Custom",true))
        override suspend fun list(organization: String,includeInactive: Boolean,after: String?): List<Hydrant>{lastOrg=organization;return if(empty || organization!="a" || (!row.active && !includeInactive))emptyList()else listOf(row)}
        override suspend fun get(organization: String,id: String)=row
        private suspend fun write(version: Long?=null){calls++;suppliedVersion=version?:0;gate?.await();if(conflict){row=row.copy(version=row.version+1,address="Server change");throw RegistryFailure(RegistryError.CONFLICT)};fail?.let { throw RegistryFailure(it) }}
        override suspend fun create(organization: String,id: String,fields: HydrantFields): Hydrant {write();row=row.copy(id=id,address=fields.address);return row}
        override suspend fun update(organization: String,id: String,fields: HydrantFields,version: Long): Hydrant{write(version);row=row.copy(address=fields.address,notes=fields.notes,version=version+1);return row}
        override suspend fun changeStatus(organization: String,id: String,status: HydrantStatus,version: Long): Hydrant{write(version);row=row.copy(status=status,version=version+1);return row}
        override suspend fun setActive(organization: String,id: String,active: Boolean,version: Long): Hydrant{write(version);row=row.copy(active=active,version=version+1);return row}
    }
    @Test fun loadingContentAndRefresh()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();assertTrue(m.state.value.loading);advanceUntilIdle();assertEquals("h",m.state.value.rows.single().id);f.row=f.row.copy(address="New");m.refresh();advanceUntilIdle();assertEquals("New",m.state.value.rows.single().address)}
    @Test fun emptyList()=runTest {val f=Fake().apply{empty=true};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertNull(m.state.value.error)}
    @Test fun refreshFailureClearsStaleContent()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();f.fail=RegistryError.NETWORK;m.refresh();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertEquals(RegistryError.NETWORK,m.state.value.error)}
    @Test fun switchingClearsDetailsAndScopesList()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.switchOrganization("b");advanceUntilIdle();assertNull(m.state.value.selected);assertEquals("b",f.lastOrg);assertFalse(m.state.value.manages)}
    @Test fun firefighterCannotEditOrDeactivate()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.requestActive();assertNull(m.state.value.form);assertFalse(m.state.value.confirmDeactivate);assertEquals(0,f.calls)}
    @Test fun managerEditsWithExpectedVersion()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.changeForm(m.state.value.form!!.copy(address="Edited"));m.save();advanceUntilIdle();assertEquals(2L,f.suppliedVersion);assertEquals("Edited",m.state.value.selected?.address);assertEquals(3L,m.state.value.selected?.version)}
    @Test fun adminEdits()=runTest {val f=Fake(RegistryRole.ADMIN);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.save();advanceUntilIdle();assertEquals(1,f.calls)}
    @Test fun validCreateReturnsCode()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();val id=m.state.value.form!!.id;m.changeForm(m.state.value.form!!.copy(type="t",address="New"));m.save();advanceUntilIdle();assertEquals(id,m.state.value.selected?.id);assertEquals("A-H-000001",m.state.value.selected?.code);assertNull(m.state.value.form)}
    @Test fun missingLocationNeverSubmits()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t"));m.save();assertEquals(0,f.calls);assertEquals(RegistryError.LOCATION,m.state.value.error)}
    @Test fun duplicateSubmitBlockedSynchronously()=runTest {val f=Fake().apply{gate=CompletableDeferred()};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t",address="New"));m.save();m.save();runCurrent();assertEquals(1,f.calls);assertTrue(m.state.value.mutating);f.gate!!.complete(Unit);advanceUntilIdle();assertFalse(m.state.value.mutating)}
    @Test fun networkFailureRetainsDraftAndUuid()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t",address="Retained"));val draft=m.state.value.form;f.fail=RegistryError.NETWORK;m.save();advanceUntilIdle();assertEquals(draft,m.state.value.form);assertFalse(m.state.value.mutating)}
    @Test fun statusUsesCurrentVersion()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.status(HydrantStatus.WORKING);advanceUntilIdle();assertEquals(2L,f.suppliedVersion);assertEquals(HydrantStatus.WORKING,m.state.value.selected?.status)}
    @Test fun conflictReloadsAndRetainsDraftForExplicitReview()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.changeForm(m.state.value.form!!.copy(address="My draft"));f.conflict=true;m.save();advanceUntilIdle();assertTrue(m.state.value.conflict);assertEquals("Server change",m.state.value.selected?.address);assertNull(m.state.value.form);assertEquals("My draft",m.state.value.reviewDraft?.address);assertEquals(1,f.calls);m.reviewDraft();assertEquals(3L,m.state.value.form?.baseVersion);assertEquals("My draft",m.state.value.form?.address)}
    @Test fun statusConflictDoesNotAutomaticallyRetry()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();f.conflict=true;m.status(HydrantStatus.WORKING);advanceUntilIdle();assertEquals(1,f.calls);assertTrue(m.state.value.conflict);assertEquals(3L,m.state.value.selected?.version)}
    @Test fun deactivateRequiresConfirmationAndCanCancel()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.requestActive();assertTrue(m.state.value.confirmDeactivate);assertEquals(0,f.calls);m.dismissDeactivate();m.confirmDeactivate();advanceUntilIdle();assertEquals(0,f.calls)}
    @Test fun deactivateAndReactivatePreserveIdentity()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.requestActive();m.confirmDeactivate();advanceUntilIdle();assertFalse(m.state.value.selected!!.active);assertTrue(m.state.value.rows.isEmpty());m.requestActive();advanceUntilIdle();assertTrue(m.state.value.selected!!.active);assertEquals("h",m.state.value.selected?.id);assertEquals("A-H-000001",m.state.value.selected?.code)}
    @Test fun includeInactiveOnlyForManagers()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.includeInactive(true);assertFalse(m.state.value.includeInactive);f.role=RegistryRole.ADMIN;f.row=f.row.copy(active=false);m.refresh();advanceUntilIdle();m.includeInactive(true);advanceUntilIdle();assertEquals(1,m.state.value.rows.size)}
    @Test fun authorizationFailureClearsProtectedData()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();f.fail=RegistryError.FORBIDDEN;m.status(HydrantStatus.WORKING);advanceUntilIdle();assertNull(m.state.value.selected);assertNull(m.state.value.organization);assertTrue(m.state.value.rows.isEmpty())}
    @Test fun logoutClearsDraftAndInFlightResult()=runTest {val f=Fake().apply{gate=CompletableDeferred()};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t",address="Private"));m.save();runCurrent();m.clear();f.gate!!.complete(Unit);advanceUntilIdle();assertEquals(RegistryState(),m.state.value)}
}
