package si.gasilko.app.feature.hydrants

import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.*
import org.junit.Assert.*
import org.junit.Test
import si.gasilko.app.feature.hydrants.domain.*
import si.gasilko.app.feature.hydrants.presentation.*

@OptIn(ExperimentalCoroutinesApi::class)
class HydrantViewModelTest {
    @Test fun searchByCode()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(search=" a-h-000001 "));m.applyFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size);assertEquals("a-h-000001",m.state.value.query.search)}
    @Test fun searchByAddress()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(search="ORIGINAL"));m.applyFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size)}
    @Test fun searchByDescriptionAndLiteralCharacters()=runTest {val f=Fake().apply{row=row.copy(description="North %_ \"gate\"")};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(search="%_ \"gate\""));m.applyFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size);m.changeFilters(m.state.value.query.copy(search="x%"));m.applyFilters();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty())}
    @Test fun combinedFiltersAndClear()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(type="t",status=HydrantStatus.UNKNOWN,search="Original"));m.applyFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size);m.changeFilters(m.state.value.query.copy(status=HydrantStatus.WORKING));m.applyFilters();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());m.clearFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size);assertFalse(m.state.value.query.filtered)}
    @Test fun typeAndBlankSearch()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(type="foreign",search=" \t\n "));m.applyFilters();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertEquals("",m.state.value.query.search);m.clearFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size)}
    @Test fun organizationSwitchResetsAllFilters()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(search="Original",type="t",status=HydrantStatus.UNKNOWN,active=ActiveFilter.ALL));m.applyFilters();advanceUntilIdle();m.switchOrganization("b");advanceUntilIdle();assertEquals(HydrantQuery("b"),m.state.value.query)}
    @Test fun inactiveOnlyForManagerAndAdmin()=runTest {for(role in listOf(RegistryRole.MANAGER,RegistryRole.ADMIN)){val f=Fake(role).apply{row=row.copy(active=false)};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());m.changeFilters(m.state.value.query.copy(active=ActiveFilter.INACTIVE));m.applyFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size)}}
    @Test fun statusMutationLeavesCurrentFilter()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(status=HydrantStatus.UNKNOWN));m.applyFilters();advanceUntilIdle();m.open("h");advanceUntilIdle();m.status(HydrantStatus.WORKING);advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertEquals(2L,f.suppliedVersion)}
    @Test fun conflictReconcilesCurrentSearchAndPreservesDraft()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(search="Original"));m.applyFilters();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.changeForm(m.state.value.form!!.copy(notes="retained"));f.conflict=true;m.save();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertEquals("retained",m.state.value.reviewDraft?.notes);m.reviewDraft();assertEquals(3L,m.state.value.form?.baseVersion)}
    @Test fun queryNormalizationRestrictsFirefighter() {val q=HydrantQuery("a",search=" X ",active=ActiveFilter.INACTIVE).normalized(RegistryRole.FIREFIGHTER);assertEquals("X",q.search);assertEquals(ActiveFilter.ACTIVE,q.active)}
    private class Fake(var role: RegistryRole = RegistryRole.MANAGER): HydrantRepository {
        var row=Hydrant("h","a","A-H-000001","t",HydrantStatus.UNKNOWN,address="Original",version=2)
        var fail: RegistryError?=null;var conflict=false;var empty=false;var calls=0;var suppliedVersion=0L;var lastOrg=""
        var gate: CompletableDeferred<Unit>?=null;var getFailure: RegistryError?=null
        override suspend fun organizations(): List<RegistryOrganization> { fail?.let { throw RegistryFailure(it) };return listOf(RegistryOrganization("a","A",role),RegistryOrganization("b","B",RegistryRole.FIREFIGHTER)) }
        override suspend fun types(organization: String)=listOf(HydrantType("t",null,"CUSTOM","Custom",true))
        override suspend fun list(query: HydrantQuery,after: String?): List<Hydrant>{lastOrg=query.organization;return if(empty)emptyList()else listOf(row).filter(query::matches)}
        override suspend fun get(organization: String,id: String): Hydrant {getFailure?.let{throw RegistryFailure(it)};return row}
        private suspend fun write(version: Long?=null){calls++;suppliedVersion=version?:0;gate?.await();if(conflict){row=row.copy(version=row.version+1,address="Server change");throw RegistryFailure(RegistryError.CONFLICT)};fail?.let { throw RegistryFailure(it) }}
        override suspend fun create(organization: String,id: String,fields: HydrantFields): Hydrant {write();row=row.copy(id=id,address=fields.address);return row}
        override suspend fun update(organization: String,id: String,fields: HydrantFields,version: Long): Hydrant{write(version);row=row.copy(address=fields.address,notes=fields.notes,version=version+1);return row}
        override suspend fun changeStatus(organization: String,id: String,status: HydrantStatus,version: Long): Hydrant{write(version);row=row.copy(status=status,version=version+1);return row}
        override suspend fun setActive(organization: String,id: String,active: Boolean,version: Long): Hydrant{write(version);row=row.copy(active=active,version=version+1);return row}
    }
    @Test fun loadingContentAndRefresh()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();assertTrue(m.state.value.loading);advanceUntilIdle();assertEquals("h",m.state.value.rows.single().id);f.row=f.row.copy(address="New");m.refresh();advanceUntilIdle();assertEquals("New",m.state.value.rows.single().address)}
    @Test fun emptyList()=runTest {val f=Fake().apply{empty=true};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertNull(m.state.value.error)}
    @Test fun refreshFailureClearsStaleContent()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();f.fail=RegistryError.NETWORK;m.refresh();advanceUntilIdle();assertTrue(m.state.value.rows.isEmpty());assertEquals(RegistryError.NETWORK,m.state.value.error)}
    @Test fun switchingClearsDetailsAndScopesList()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.switchOrganization("b");advanceUntilIdle();assertNull(m.state.value.selected);assertEquals("b",f.lastOrg);assertFalse(m.state.value.manages)}
    @Test fun firefighterCannotEditOrDeactivate()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.requestActive();assertNull(m.state.value.form);assertFalse(m.state.value.confirmDeactivate);assertEquals(0,f.calls)}
    @Test fun managerEditsWithExpectedVersion()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.changeForm(m.state.value.form!!.copy(address="Edited"));m.save();advanceUntilIdle();assertEquals(2L,f.suppliedVersion);assertEquals("Edited",m.state.value.selected?.address);assertEquals(3L,m.state.value.selected?.version)}
    @Test fun adminEdits()=runTest {val f=Fake(RegistryRole.ADMIN);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.save();advanceUntilIdle();assertEquals(1,f.calls)}
    @Test fun validCreateReturnsCode()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();val id=m.state.value.form!!.id;m.changeForm(m.state.value.form!!.copy(type="t",address="New"));m.save();advanceUntilIdle();assertEquals(id,m.state.value.selected?.id);assertEquals("A-H-000001",m.state.value.selected?.code);assertNull(m.state.value.form)}
    @Test fun missingLocationNeverSubmits()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t"));m.save();assertEquals(0,f.calls);assertEquals(RegistryError.LOCATION,m.state.value.error)}
    @Test fun duplicateSubmitBlockedSynchronously()=runTest {val f=Fake().apply{gate=CompletableDeferred()};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t",address="New"));m.save();m.save();runCurrent();assertEquals(1,f.calls);assertTrue(m.state.value.mutating);f.gate!!.complete(Unit);advanceUntilIdle();assertFalse(m.state.value.mutating)}
    @Test fun networkFailureRetainsDraftAndUuid()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t",address="Retained"));val draft=m.state.value.form;f.fail=RegistryError.NETWORK;m.save();advanceUntilIdle();assertEquals(draft,m.state.value.form);assertFalse(m.state.value.mutating)}
    @Test fun statusUsesCurrentVersion()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.status(HydrantStatus.WORKING);advanceUntilIdle();assertEquals(2L,f.suppliedVersion);assertEquals(HydrantStatus.WORKING,m.state.value.selected?.status)}
    @Test fun conflictReloadsAndRetainsDraftForExplicitReview()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.edit();m.changeForm(m.state.value.form!!.copy(address="My draft"));f.conflict=true;m.save();advanceUntilIdle();assertTrue(m.state.value.conflict);assertEquals("Server change",m.state.value.selected?.address);assertNull(m.state.value.form);assertEquals("My draft",m.state.value.reviewDraft?.address);assertEquals(1,f.calls);m.reviewDraft();assertEquals(3L,m.state.value.form?.baseVersion);assertEquals("My draft",m.state.value.form?.address)}
    @Test fun statusConflictDoesNotAutomaticallyRetry()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();f.conflict=true;m.status(HydrantStatus.WORKING);advanceUntilIdle();assertEquals(1,f.calls);assertTrue(m.state.value.conflict);assertEquals(3L,m.state.value.selected?.version)}
    @Test fun deactivateRequiresConfirmationAndCanCancel()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.requestActive();assertTrue(m.state.value.confirmDeactivate);assertEquals(0,f.calls);m.dismissDeactivate();m.confirmDeactivate();advanceUntilIdle();assertEquals(0,f.calls)}
    @Test fun deactivateAndReactivatePreserveIdentity()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();m.requestActive();m.confirmDeactivate();advanceUntilIdle();assertFalse(m.state.value.selected!!.active);assertTrue(m.state.value.rows.isEmpty());m.requestActive();advanceUntilIdle();assertTrue(m.state.value.selected!!.active);assertEquals("h",m.state.value.selected?.id);assertEquals("A-H-000001",m.state.value.selected?.code)}
    @Test fun includeInactiveOnlyForManagers()=runTest {val f=Fake(RegistryRole.FIREFIGHTER);val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(active=ActiveFilter.ALL));m.applyFilters();assertEquals(ActiveFilter.ACTIVE,m.state.value.query.active);f.role=RegistryRole.ADMIN;f.row=f.row.copy(active=false);m.refresh();advanceUntilIdle();m.changeFilters(m.state.value.query.copy(active=ActiveFilter.ALL));m.applyFilters();advanceUntilIdle();assertEquals(1,m.state.value.rows.size)}
    @Test fun authorizationFailureClearsProtectedData()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();f.fail=RegistryError.FORBIDDEN;m.status(HydrantStatus.WORKING);advanceUntilIdle();assertNull(m.state.value.selected);assertNull(m.state.value.organization);assertTrue(m.state.value.rows.isEmpty())}
    @Test fun logoutClearsDraftAndInFlightResult()=runTest {val f=Fake().apply{gate=CompletableDeferred()};val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.add();m.changeForm(m.state.value.form!!.copy(type="t",address="Private"));m.save();runCurrent();m.clear();f.gate!!.complete(Unit);advanceUntilIdle();assertEquals(RegistryState(),m.state.value)}
    @Test fun failedConflictReloadRecoversExactDetailOnRefresh()=runTest {val f=Fake();val m=HydrantViewModel(f,this);m.refresh();advanceUntilIdle();m.open("h");advanceUntilIdle();f.conflict=true;f.getFailure=RegistryError.NETWORK;m.status(HydrantStatus.WORKING);advanceUntilIdle();assertNull(m.state.value.selected);assertEquals("h",m.state.value.reloadId);f.getFailure=null;m.refresh();advanceUntilIdle();assertEquals(3L,m.state.value.selected?.version);assertTrue(m.state.value.conflict);assertEquals(1,f.calls)}
}
